apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-08-09T09:08:59Z
  generation: 5
  labels:
    app: cloudnative
  name: cloudnative
  namespace: mattit
  resourceVersion: "50688987"
  selfLink: /oapi/v1/namespaces/mattit/deploymentconfigs/cloudnative
  uid: d9fa433f-9bb3-11e8-808f-0050568839ad
spec:
  replicas: 1
  selector:
    app: cloudnative
    deploymentconfig: cloudnative
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: cloudnative
        deploymentconfig: cloudnative
    spec:
      containers:
      - image: 172.30.79.111:5000/mattit/cloudnative@sha256:a344077103ab42e3340b538d990b4ffdb3f5875faa4c09cbab4132fb05adb461
        imagePullPolicy: Always
        name: cloudnative
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - cloudnative
      from:
        kind: ImageStreamTag
        name: cloudnative:latest
        namespace: mattit
      lastTriggeredImage: 172.30.79.111:5000/mattit/cloudnative@sha256:a344077103ab42e3340b538d990b4ffdb3f5875faa4c09cbab4132fb05adb461
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-09T09:10:11Z
    lastUpdateTime: 2018-08-09T09:10:11Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-09T09:21:38Z
    lastUpdateTime: 2018-08-09T09:21:40Z
    message: replication controller "cloudnative-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
